// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2d861b8e-347f-47be-b20a-e915bf99f099",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PSpSixwII",
    "aws_user_pools_web_client_id": "qlqc9032hset7uot895drqvcu",
    "aws_mobile_analytics_app_id": "38f8ec4234d84927a58edee122869042",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
